version: 2.1

jobs:
  build:
    docker:
     - image: circleci/node:current
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: 'npm-packages'
          paths:
            - /src/node_modules
      - run: npm run lint

  test:
    docker:
      - image: circleci/node:current
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm run test

  analyze:
    docker: 
      - image: circleci/node:current
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm audit


workflows:
  myworkflow: 
    jobs:
      - build
      - test:
        requires:
          - build
      - analyze:
        requires:
          - test

